development:
  adapter: postgresql
  encoding: utf8
      <% if Rails.application.secrets[:pgsql].present? %>
    host: <%= Rails.application.secrets[:pgsql][:url]%>
    username: <%= Rails.application.secrets[:pgsql][:user]%>
    password: <%= Rails.application.secrets[:pgsql][:password]%>
      <% end %>

test:
  adapter: postgresql
  encoding: utf8
    <% if Rails.application.secrets[:pgsql].present? %>
    host: <%= Rails.application.secrets[:pgsql][:url]%>
    username: <%= Rails.application.secrets[:pgsql][:user]%>
    password: <%= Rails.application.secrets[:pgsql][:password]%>
    <% end %>

production:
  adapter: postgresql
  encoding: utf8
  <% if Rails.application.secrets[:pgsql].present? %>
    host: <%= Rails.application.secrets[:pgsql][:url]%>
    username: <%= Rails.application.secrets[:pgsql][:user]%>
    password: <%= Rails.application.secrets[:pgsql][:password]%>
  <% end %>