default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.postgresql

test:
  <<: *default
  database: db/test.postgres

production:
  encoding: utf8
  <% if Rails.application.secrets[:pgsql].present? %>
    host: <%= Rails.application.secrets[:pgsql][:url]%>
    username: <%= Rails.application.secrets[:pgsql][:user]%>
    password: <%= Rails.application.secrets[:pgsql][:password]%>
  <% end %>