default: &default
  database: postgres
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  username: postgres
  password: 12345

test:
  <<: *default
  username: postgres
  password: 12345

production:
  <<: *default
  username: postgres
  password: 12345